start_date: "2021-01-01"
end_date: "2026-01-01"
equidistant: true
num_samples: 120
max_parallel: 5

buffer_m: 100
target_res_m: 10

sensors:
  S2:
    bands: [B02, B03, B04, B08, B11, B12]
    cloud_cover: 20
  S1:
    polarizations: [VV, VH]
  S3:
    products: [lst-in]
  # ERA5:
  #   variable: tp
  #   daily_agg: sum
  # MODIS:
  #   products: [ET_500m, PET_500m]
