paths:
  aoi_table: /Users/ivanr/Developer/ai-vineyard-productivity/agrixel-fair-dockerV2/data/input/aoi_table.csv



stats:
  - mean
  # - std
  # - median

sensors:
  SENTINEL-2:
    compute_indices:
      - NDVI
      - EVI
      # - SAVI
      # - NBR2
      # - NDWI
    output_bands:
      - NDVI
      - EVI
      # - SAVI
      # - NBR2
      # - NDWI
      # - B04   # Red
      # - B08   # NIR
      # - B11   # SWIR1

  SENTINEL-1:
    compute_indices:
      - RVI
      - VH_VV
      # - DpRVI
    output_bands:
      # - VV
      # - VH
      - RVI
      - VH_VV
      # - DpRVI

  SENTINEL-3:
    compute_indices:
      - LST_C
    output_bands:
      - LST
      - LST_C
