#!/usr/bin/env bash
# Prepare and submit the SLURM array job.
#
# Usage:
#   bash hpc/submit.sh [--parcels-at-once N] [--dry-run]
#
# Options:
#   --parcels-at-once N   Max parcels downloading simultaneously (default: 5).
#                         Each parcel runs N_SENSORS tasks in parallel, so the
#                         actual SLURM concurrency limit = N × N_SENSORS.
#   --dry-run             Print what would be submitted without submitting.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AOI_TABLE="$REPO_DIR/data/input/aoi_table.csv"
RUN_CONFIG="$REPO_DIR/cli_app/run_config.yml"
JOB_SCRIPT="$REPO_DIR/hpc/job_array.sh"
JOB_CONFIG="$REPO_DIR/hpc/.job_config"

PARCELS_AT_ONCE=5
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --parcels-at-once) PARCELS_AT_ONCE="$2"; shift ;;
        --dry-run) DRY_RUN=true ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
    shift
done

# ── Check dependencies ─────────────────────────────────────────────────────
if [[ ! -f "$AOI_TABLE" ]]; then
    echo "ERROR: aoi_table.csv not found at $AOI_TABLE"
    exit 1
fi

if ! python -c "import yaml" &>/dev/null; then
    echo "ERROR: python/yaml not available. Activate the conda env first:"
    echo "  conda activate agrixel-fair"
    exit 1
fi

# ── Read enabled sensors from run_config.yml ──────────────────────────────
SENSORS_STR=$(python - <<EOF
import yaml
cfg = yaml.safe_load(open("$RUN_CONFIG"))
enabled = [k for k, v in (cfg.get("sensors") or {}).items() if v is not None]
print(" ".join(enabled))
EOF
)

if [[ -z "$SENSORS_STR" ]]; then
    echo "ERROR: no sensors enabled in $RUN_CONFIG"
    exit 1
fi

# shellcheck disable=SC2206
SENSORS=($SENSORS_STR)
N_SENSORS=${#SENSORS[@]}

# ── Count parcels ──────────────────────────────────────────────────────────
N_PARCELS=$(( $(wc -l < "$AOI_TABLE") - 1 ))

# ── Compute array params ───────────────────────────────────────────────────
N_TASKS=$(( N_PARCELS * N_SENSORS ))
MAX_CONCURRENT=$(( PARCELS_AT_ONCE * N_SENSORS ))

echo "Parcels       : $N_PARCELS"
echo "Sensors       : ${SENSORS[*]}  ($N_SENSORS)"
echo "Total tasks   : $N_TASKS  ($N_PARCELS × $N_SENSORS)"
echo "Parcels at once: $PARCELS_AT_ONCE  → $MAX_CONCURRENT concurrent tasks"

# ── Write .job_config (sourced by job_array.sh at runtime) ────────────────
cat > "$JOB_CONFIG" << EOF
# Auto-generated by submit.sh — do not edit manually.
N_PARCELS=$N_PARCELS
N_SENSORS=$N_SENSORS
SENSORS=(${SENSORS[*]})
EOF
echo "Written: $JOB_CONFIG"

# ── Patch --array line in job_array.sh ────────────────────────────────────
sed -i.bak "s|^#SBATCH --array=.*|#SBATCH --array=1-${N_TASKS}%${MAX_CONCURRENT}|" "$JOB_SCRIPT"
echo "Updated: job_array.sh → --array=1-${N_TASKS}%${MAX_CONCURRENT}"

mkdir -p "$REPO_DIR/hpc/logs"

# ── Submit ─────────────────────────────────────────────────────────────────
CMD="sbatch $JOB_SCRIPT"
echo "Command: $CMD"
if $DRY_RUN; then
    echo "[DRY RUN] Not submitting."
else
    $CMD
fi
